export const actions = {
    CLEAR_SEARCH_RESULTS: 'CLEAR_SEARCH_RESULTS',

    SET_CURRENT_SEARCH: 'SET_CURRENT_SEARCH',
    SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
    SET_RELATED_RESULTS: 'SET_RELATED_RESULTS'
} as const